# run:
#   timeout: 5m
#   modules-download: readonly

# linters:
#   enable:
#     - errcheck
#     - gosimple
#     - govet
#     - ineffassign
#     - staticcheck
#     - typecheck
#     - unused
#     - gofmt
#     - goimports
#     - misspell
#     - gocritic
#     - revive

# linters-settings:
#   errcheck:
#     check-type-assertions: true
#   gocritic:
#     enabled-tags:
#      - diagnostic
#      - experimental
#      - opinionated
#      - performance
#      - style
#   revive:
#     rules:
#       - name: exported     


# lint:
#  golangci-lint run ./...

#! REFACTORED FOR LATEST VERSION - 
version: "2"

run:
  timeout: 5m

linters:
  default: standard
    
